const word = ["apple", "banana", "carrot", "dog", "elephant", "fish", "giraffe", "honey", "igloo", "jacket",
"kite", "lemon", "mountain", "notebook", "orange", "piano", "quilt", "rose", "sunflower", "tree",
"umbrella", "violin", "whale", "xylophone", "yacht", "zebra", "adventure", "brave", "courage", "dream",
"energy", "fantasy", "genuine", "hope", "imagination", "joy", "kindness", "laughter", "mystery", "nature",
"ocean", "peace", "quest", "rainbow", "sparkle", "trust", "universe", "victory", "wonder", "yarn",
"zest", "amber", "blossom", "candle", "dawn", "echo", "flame", "glimmer", "harmony", "inspire",
"jewel", "kaleidoscope", "light", "moon", "nest", "oasis", "petal", "quasar", "river", "star",
"tide", "utopia", "vivid", "whisper", "azure", "breeze", "cloud", "dusk", "ember", "frost",
"gem", "horizon", "island", "jungle", "key", "leaf", "mosaic", "nectar", "opal", "quicksilver",
"rosebud", "sapphire", "tangerine", "unicorn", "violet", "wish", "yonder", "zenith", "adorn", "bloom",
"courageous", "delightful", "effervescent", "flourish", "glistening", "happiness", "illuminate", "jubilant", "kinder", "luminescent",
"melody", "novel", "optimistic", "playful", "quaint", "radiant", "serenade", "tranquil", "uplift", "vibrant",
"whimsical", "xenial", "yearn", "zephyr", "artistry", "balance", "canvas", "daring", "elegance", "finesse",
"graceful", "hues", "intrigue", "jovial", "kudos", "legacy", "mirth", "nurture", "opulent", "plush",
"quench", "resilience", "serendipity", "tenacity", "unity", "versatile", "wisdom", "x-factor", "youthful", "zeal",
"abundance", "bounty", "clarity", "depth", "exuberance", "fervor", "glow", "heartfelt", "infinity", "jubilance",
"keystone", "luminary", "mojo", "nexus", "oracle", "pinnacle", "quicksand", "revive", "sublime", "transcend",
"uplifted", "vortex", "whirlwind", "xenon", "yoke", "zodiac", "aspire", "bliss", "catharsis", "diligence",
"euphoria", "fable", "gravity", "horizon", "invigorate", "jigsaw", "kaleidoscopic", "labyrinth", "melancholy", "novelty",
"overture", "paradise", "quasar", "reverie", "synthesis", "traverse", "unveil", "vanguard", "whimsy", "xenophobic",
"yearning", "zealot", "alchemy", "basking", "cascading", "dappled", "eclipse", "fable", "gossamer", "halcyon"]
let chosen = word[Math.flo